# Generated by Django 4.2.1 on 2023-06-20 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_mailbox_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flat'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.floor'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.section'),
        ),
    ]
