# Generated by Django 4.2.1 on 2023-06-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_mailbox_flat_mailbox_floor_mailbox_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.house', verbose_name='Дом'),
        ),
    ]
