# Generated by Django 4.2.1 on 2023-06-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_flat_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.tariffsystem'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='date_published',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ReceiptService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('consumption', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('measure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.measure', verbose_name='Ед. изм.')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.receipt')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.service', verbose_name='Услуга')),
            ],
            options={
                'db_table': 'receipt-service',
            },
        ),
    ]
