# Generated by Django 4.2.1 on 2023-06-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_remove_tariffsystem_tariff_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffservice',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
