# Generated by Django 4.2.1 on 2023-06-06 20:19

import admin_panel.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_tariffservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='img',
            field=models.ImageField(null=True, upload_to=admin_panel.utilities.get_timestamp_path),
        ),
        migrations.AlterField(
            model_name='infogallery',
            name='img',
            field=models.ImageField(null=True, upload_to=admin_panel.utilities.get_timestamp_path),
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='currency',
            field=models.CharField(blank=True, default='грн', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.service', verbose_name='Услуга'),
        ),
    ]
