# Generated by Django 4.2.1 on 2023-06-06 22:14

import admin_panel.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_alter_gallery_img_alter_infogallery_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='img',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to=admin_panel.utilities.get_timestamp_path)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.gallery')),
            ],
            options={
                'db_table': 'photo',
            },
        ),
    ]
