# Generated by Django 4.2.1 on 2023-06-06 22:24

import admin_panel.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_remove_gallery_img_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('img', models.ImageField(null=True, upload_to=admin_panel.utilities.get_timestamp_path)),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.gallery')),
            ],
            options={
                'db_table': 'info_photo',
            },
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='extra_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_gallery_about', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_about', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_main', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='info_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_gallery_main', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='sevicesite',
            name='info_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_gallery_service', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='tariffsite',
            name='info_gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_gallery_tariff', to='admin_panel.gallery'),
        ),
        migrations.DeleteModel(
            name='InfoGallery',
        ),
    ]
