# Generated by Django 4.2.1 on 2023-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_paybox_is_complete_paybox_personal_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paybox',
            name='debit_credit',
            field=models.CharField(choices=[('plus', 'Приход'), ('minus', 'Расход')], default='plus', max_length=100, verbose_name='Приход/расход'),
        ),
    ]
