# Generated by Django 4.2.1 on 2023-06-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_infophoto_alter_aboutus_extra_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
