# Generated by Django 4.2.1 on 2023-06-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_paybox_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_published',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
