# Generated by Django 4.2.1 on 2023-06-07 06:00

import admin_panel.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_alter_mainpage_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='document',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='info_gallery',
        ),
        migrations.AlterField(
            model_name='infophoto',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=admin_panel.utilities.get_timestamp_path, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='gallery_main', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='show_app_links',
            field=models.BooleanField(default=True, verbose_name=' Показать ссылки на приложения'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_set', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=admin_panel.utilities.get_timestamp_path, verbose_name=''),
        ),
        migrations.CreateModel(
            name='AboutUsDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='docs/<function get_timestamp_path at 0x7f7d93b95bd0>', verbose_name='')),
                ('about_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.aboutus')),
            ],
            options={
                'db_table': 'about_us_document',
            },
        ),
    ]
