# Generated by Django 4.2.1 on 2023-06-07 06:31

import admin_panel.utilities
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_remove_aboutus_document_remove_mainpage_info_gallery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='director_photo',
            field=models.ImageField(blank=True, null=True, upload_to=admin_panel.utilities.get_timestamp_path, verbose_name='Рекомендуемый размер: (250x310)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='gallery_about', to='admin_panel.gallery'),
        ),
        migrations.AlterField(
            model_name='aboutusdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='docs/<function get_timestamp_path at 0x7fbcd39b3f40>', verbose_name=''),
        ),
    ]
