# Generated by Django 4.2.1 on 2023-06-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_alter_receipt_date_published_alter_receipt_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date_published',
            field=models.DateField(default='2012-12-12'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='end_date',
            field=models.DateField(default='2012-12-12'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='start_date',
            field=models.DateField(default='2012-12-12'),
        ),
    ]
