# Generated by Django 4.2.1 on 2023-07-01 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_receipt_date_published_alter_receipt_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='flat_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.flatowner'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('', 'Выберите...'), ('new', 'Новое'), ('in work', 'В работе'), ('complete', 'Выполнено')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
