# Generated by Django 4.2.1 on 2023-07-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_alter_application_flat_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='flat_owner',
        ),
    ]
