# Generated by Django 4.2.1 on 2023-06-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_sevicesite_info_gallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusdocument',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название документа'),
        ),
    ]
