# Generated by Django 4.2.1 on 2023-07-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_application_flat_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptExcelDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='')),
                ('file', models.FileField(upload_to='receipt', verbose_name='Загрузить пользовательский шаблон')),
            ],
            options={
                'db_table': 'receipt_excel_doc',
            },
        ),
    ]
