# Generated by Django 4.2.1 on 2023-06-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_aboutusdocument_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseUser',
            new_name='Personal',
        ),
        migrations.AlterModelTable(
            name='personal',
            table='personal',
        ),
    ]
