# Generated by Django 4.2.1 on 2023-07-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_receiptexceldoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptexceldoc',
            name='by_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='receiptexceldoc',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Название'),
        ),
    ]
