# Generated by Django 4.2.1 on 2023-07-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_receiptexceldoc_by_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='indication',
            name='indication_val',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, verbose_name='Показания'),
        ),
    ]
