# Generated by Django 4.2.1 on 2023-06-12 11:35

import admin_panel.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatowner',
            name='avatar',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=admin_panel.utilities.get_timestamp_path, verbose_name='Сменить изображение'),
        ),
    ]
