# Generated by Django 4.2.1 on 2023-06-13 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_remove_flatowner_avatar_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
