# Generated by Django 4.2.1 on 2023-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_alter_receiptservice_consumption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterModelOptions(
            name='flatowner',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='indication',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterModelOptions(
            name='paybox',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='personalaccount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterModelOptions(
            name='tariffsystem',
            options={'ordering': ['-date_edited']},
        ),
        migrations.AlterField(
            model_name='personal',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('manager', 'Управляющий'), ('accountant', 'Бухгалтер'), ('electrician', 'Электрик'), ('plumber', 'Сантехник'), ('locksmith', 'Слесарь')], default='director', max_length=50, verbose_name='Роль'),
        ),
    ]
