# Generated by Django 4.2.1 on 2023-07-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_alter_application_options_alter_flatowner_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='square',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Площадь (кв.м.)'),
        ),
    ]
