# Generated by Django 4.2.1 on 2023-06-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_remove_house_users_houseuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='houseuser',
            unique_together={('user', 'house')},
        ),
    ]
