# Generated by Django 4.2.1 on 2023-06-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_alter_houseuser_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.personal'),
        ),
    ]
