# Generated by Django 4.2.1 on 2023-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_alter_houseuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatowner',
            name='ID',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
