# Generated by Django 4.2.1 on 2023-07-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_mailbox_unread_alter_flatowner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('statistics', models.BooleanField(default=False)),
                ('paybox', models.BooleanField(default=False)),
                ('receipt', models.BooleanField(default=False)),
                ('personal_account', models.BooleanField(default=False)),
                ('flat', models.BooleanField(default=False)),
                ('flat_owner', models.BooleanField(default=False)),
                ('house', models.BooleanField(default=False)),
                ('mailbox', models.BooleanField(default=False)),
                ('application', models.BooleanField(default=False)),
                ('indication', models.BooleanField(default=False)),
                ('manage_site', models.BooleanField(default=False)),
                ('service', models.BooleanField(default=False)),
                ('tariff', models.BooleanField(default=False)),
                ('role', models.BooleanField(default=False)),
                ('users', models.BooleanField(default=False)),
                ('payment_detail', models.BooleanField(default=False)),
                ('payment_article', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
