# Generated by Django 4.2.1 on 2023-06-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_flatowner_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flatowner',
            name='flat',
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.flatowner'),
        ),
    ]
