# Generated by Django 4.2.1 on 2023-06-15 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_alter_flat_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='flat_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.flatowner', verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.floor', verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.section', verbose_name='Секция'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.tariffsystem', verbose_name='Тариф'),
        ),
    ]
