# Generated by Django 4.2.1 on 2023-06-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_alter_flat_flat_owner_alter_flat_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.flat', verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.house', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.section', verbose_name='Секция'),
        ),
    ]
