# Generated by Django 4.2.1 on 2023-06-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_alter_personalaccount_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_account', to='admin_panel.flat', verbose_name='Квартира'),
        ),
    ]
