# Generated by Django 4.2.1 on 2023-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_alter_personalaccount_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='number',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='№'),
        ),
    ]
