# Generated by Django 4.2.1 on 2023-06-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_alter_personalaccount_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='indication',
            name='indication_val',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='indication',
            name='date_published',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
