# Generated by Django 4.2.1 on 2023-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_indication_indication_val_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indication',
            options={'ordering': ['date_published']},
        ),
        migrations.AlterField(
            model_name='indication',
            name='indication_val',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Показания'),
        ),
    ]
