# Generated by Django 4.2.1 on 2023-06-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_alter_indication_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indication',
            options={},
        ),
    ]
